# Generated by Django 6.0 on 2026-03-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
