# Generated by Django 6.0 on 2026-03-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_issue_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
